---
apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  name: restic
  namespace: heptio-ark
spec:
  selector:
    matchLabels:
      name: restic
  template:
    metadata:
      labels:
        name: restic
    spec:
      serviceAccountName: ark
      securityContext:
        runAsUser: 0
      volumes:
        - name: plugins
          emptyDir: {}
        - name: scratch
          emptyDir: {}
      containers:
        - name: ark
          image: gcr.io/heptio-images/ark:latest
          command: ["/ark"]
          args: ["restic", "server"]
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: HEPTIO_ARK_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: access_key
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: secret_key
            - name: ARK_SCRATCH_DIR
              value: /scratch
          volumeMounts:
            - name: plugins
              mountPath: /plugins
            - name: scratch
              mountPath: /scratch
