---
kind: pipeline
name: master

steps:
  - name: tests
    image: alpine
    commands:
      - echo "test-example"

  - name: build
    image: alpine
    commands:
      - echo "buld-example"

  - name: staging
    image: alpine
    commands:
      - echo "staging-example"

trigger:
  event:
    - merge
    - push
  branch:
    - master
---
kind: pipeline
name: pr

steps:
  - name: tests
    image: alpine
    commands:
      - echo "test-eexample"
      - printenv
    when:
      event: pull_request