---
kind: pipeline
name: master

steps:
  - name: tests
    image: alpine
    commands:
      - echo "test-example"

  - name: build
    image: alpine
    commands:
      - echo "build-exampffffffle"

  - name: staging
    image: alpine
    commands:
      - echo "staging-example"

trigger:
  event:
    - merge
    - push
  branch:
    - master
---
kind: pipeline
name: pr

steps:
  - name: foo1
    image: alpine
    commands:
      - echo "foo111"
  - name: foo2
    image: alpine
    commands:
      - echo "foo2"
  - name: foo3
    image: alpine
    commands:
      - echo "foo3"
  - name: foo4
    image: alpine
    commands:
      - echo "foo4"
    depends_on: [ foo1, foo2, foo3 ]
trigger:
  event:
    - pull_request

---
kind: pipeline
name: switch

steps:
  - name: switch
    image: alpine
    commands:
      - echo "switched"
    when:
      target: switch

trigger:
  event:
    - promote
