---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: drone
  namespace: cicd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: drone
  namespace: cicd
rules:
  - apiGroups: [""]
    resources: ["pods/portforward"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list"]
  - apiGroups: ["extensions"]
    resources: ["deployments"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: drone
  namespace: cicd
subjects:
  - kind: ServiceAccount
    name: drone
    namespace: cicd
roleRef:
  kind: ClusterRole
  name: drone
  apiGroup: rbac.authorization.k8s.io
