---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: jenkins
  namespace: cicd
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: jenkins
    spec:
      volumes:
        - name: jenkins-home
          persistentVolumeClaim:
            claimName: jenkins-data-claim
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
        - name: docker-storage
          emptyDir: {}
      serviceAccountName: jenkins
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - name: master
          image: risla8/jenkins
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
            - name: jnlp
              containerPort: 50000
          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home
            - name: docker-sock
              mountPath: /var/run/docker.sock
            - name: docker-storage
              mountPath: /var/lib/docker
          resources:
            requests:
              cpu: 50m
              memory: 256Mi
            limits:
              cpu: 2000m 
              memory: 2048Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-data-claim
  namespace: cicd
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: standard
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: cicd
spec:
  selector:
    name: jenkins
  type: NodePort
  ports:
    - name: http
      targetPort: http
      port: 8080
      nodePort: 32015
    - name: jnlp
      targetPort: jnlp
      port: 50000
